apiVersion: v1
name: xiaoqing-extension-6-10-long-name-long-name-long-name-long-name-long-name-long-name

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 1.0.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: "1.0.0"

description: Considering all of these possibilities above, the most promising way is → Helm chart as the input of extension installer, it provides enough flexibility and cover all known requirements. Meanwhile, Helm is the default package management tool of Kyma, so it is not necessary to introduce Kustomize as another comparable tool. Considering all of these possibilities above, the most promising way is → Helm chart as the input of extension installer, it provides enough flexibility and cover all known requirements. Meanwhile, Helm is the default package management tool of Kyma, so it is not necessary to introduce Kustomize as another comparable tool. xiaoqing

# A URL to an SVG or PNG image to be used as an icon
icon: http://t8.baidu.com/it/u=2857883419,1187496708icon: http://t8.baidu.com/it/u=2857883419,1187496708${application_icon}fm=79${application_icon}app=86${application_icon}f=JPEG?w=1280${application_icon}h=763fm=79icon: http://t8.baidu.com/it/u=2857883419,1187496708${application_icon}fm=79${application_icon}app=86${application_icon}f=JPEG?w=1280${application_icon}h=763app=86icon: http://t8.baidu.com/it/u=2857883419,1187496708${application_icon}fm=79${application_icon}app=86${application_icon}f=JPEG?w=1280${application_icon}h=763f=JPEG?w=1280icon: http://t8.baidu.com/it/u=2857883419,1187496708${application_icon}fm=79${application_icon}app=86${application_icon}f=JPEG?w=1280${application_icon}h=763h=763
